### ISSUE TITLE
[OTHER] Improving the UI of the login page of dummygram

### ISSUE THREAD

**Issue by kartikkc** [narayan954/dummygram#426] opened 2023-06-03 16:30 UTC
### What would you like to share?

I'm from GSSOC'23 and I noticed that the login page in dark looks primitive.

I would Like to improve the UI of the dummygram. It can be made more materialistic which will look soothing and the UI will be better for the User-Experience.

Assign me this issue. I would like to contribute to this project.

**Comment by narayan954** [comment] 2023-06-03 20:21
> ### What would you like to share?
> I'm from GSSOC'23 and I noticed that the login page in dark looks primitive.
> 
> I would Like to improve the UI of the dummygram. It can be made more materialistic which will look soothing and the UI will be better for the User-Experience.
> 
> Assign me this issue. I would like to contribute to this project.

hi @kartikkc this issue is a duplicate of issue #265, please claim that only... i've to close this as duplicate issue...

**Closed by narayan954** 2023-06-03 20:21 UTC
