### ISSUE TITLE
[FEATURE] Show post likers list 

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#370] opened 2023-05-27 22:12 UTC
### Description

 Show post liker list on clicking likes quantity. 

### Additional information

It could be a modal with list of usernames who liked the post and clicking those username should open their profile(this is an already existing feature, just implement it here)

**Comment by narayan954** [comment] 2023-05-29 14:59
> I would like to work on this issue if it involves only frontend as GSSOC contributor. Let me know please

okay it shall be on react,but you'll be calling a function to the database.You won't need to go out of react which means it is technically frontend.
Let me give you a snapshot of the database
![image](https://github.com/narayan954/dummygram/assets/77617189/9299c6c6-6b35-4360-8d66-78f67b6cc880)
as you can see going from left to right in database snapshot, in an individual post, there's a field likecount, in which user id of users who liked the post is stored. 
So one way to display them would be to display a modal which fetches the user details of the users whose userIds are present in the likecount array. and those list items can be clicked as a button to navigate to their profile.

I hope this helps in making a decision. :)

**Comment by Prakriti2003** [comment] 2023-05-29 16:35
I would like to work on this issue under GSSOC'23. I am comfortable with both frontend and backend.

**Comment by VijayalakshmiGanesh** [comment] 2023-05-29 16:46
> > I would like to work on this issue if it involves only frontend as GSSOC contributor. Let me know please
> 
> okay it shall be on react,but you'll be calling a function to the database.You won't need to go out of react which means it is technically frontend. Let me give you a snapshot of the database ![image](https://user-images.githubusercontent.com/77617189/241757696-9299c6c6-6b35-4360-8d66-78f67b6cc880.png) as you can see going from left to right in database snapshot, in an individual post, there's a field likecount, in which user id of users who liked the post is stored. So one way to display them would be to display a modal which fetches the user details of the users whose userIds are present in the likecount array(you may take inspiration from profile component). and those list items can be clicked as a button to navigate to their profile.
> 
> I hope this helps in making a decision.Feel free to make any decision :)

I will take it up !

**Comment by narayan954** [comment] 2023-05-29 16:56
> I would like to work on this issue under GSSOC'23. I am comfortable with both frontend and backend.

Prakriti it's claimed, sorry, You can work on the other issue assigned to you

**Comment by narayan954** [comment] 2023-05-29 16:57
> > > I would like to work on this issue if it involves only frontend as GSSOC contributor. Let me know please
> > 
> > 
> > okay it shall be on react,but you'll be calling a function to the database.You won't need to go out of react which means it is technically frontend. Let me give you a snapshot of the database ![image](https://user-images.githubusercontent.com/77617189/241757696-9299c6c6-6b35-4360-8d66-78f67b6cc880.png) as you can see going from left to right in database snapshot, in an individual post, there's a field likecount, in which user id of users who liked the post is stored. So one way to display them would be to display a modal which fetches the user details of the users whose userIds are present in the likecount array(you may take inspiration from profile component). and those list items can be clicked as a button to navigate to their profile.
> > I hope this helps in making a decision.Feel free to make any decision :)
> 
> I will take it up ! Kindly assign it to me

Yes, sure go ahead!

**Comment by Palakkgoyal** [comment] 2023-06-12 10:10
@Prakriti2003 are you working on this issue or can I take this up if you are not?

**Comment by narayan954** [comment] 2023-06-16 23:04
> @Prakriti2003 are you working on this issue or can I take this up if you are not?

we're trying to resolve this issue using Firebase admin SDK but it's having conflicts with normal SDK, so searching for the workaround.

**Comment by Palakkgoyal** [comment] 2023-06-17 06:27
Ohkk. Got it

**Comment by Palakkgoyal** [comment] 2023-06-24 18:04
Hey @narayan954  I think I can solve this issue. Can you please assign it to me.

**Comment by VijayalakshmiGanesh** [comment] 2023-06-25 05:24
> Hey @narayan954 I think I can solve this issue. Can you please assign it to me.

Hey,  I have already completed half of the work (UI part). However, I'm stuck with the firebase admin setup part. Perhaps we can collaborate together to close this issue. You can handle the setup part, and I can focus on the displaying in UI. Let's work together to resolve the issue effectively @Palakkgoyal  .

 @narayan954

**Comment by Palakkgoyal** [comment] 2023-06-25 12:04
Yes, sure I would love to collab but, the problem is with the distribution of score. I think you should change this issue to display of post likes and I will create a new issue for admin setup. Then, we will connect both.
What do you think?

**Comment by narayan954** [comment] 2023-06-25 18:40
> > Hey @narayan954 I think I can solve this issue. Can you please assign it to me.
> 
> Hey, I have already completed half of the work (UI part). However, I'm stuck with the firebase admin setup part. Perhaps we can collaborate together to close this issue. You can handle the setup part, and I can focus on the displaying in UI. Let's work together to resolve the issue effectively @Palakkgoyal .
> 
> @narayan954

that works!

**Comment by narayan954** [comment] 2023-06-25 18:41
> Yes, sure I would love to collab but, the problem is with the distribution of score. I think you should change this issue to display of post likes and I will create a new issue for admin setup. Then, we will connect both. What do you think?

I agree on this as well. Also, it'd be level 2 prs each, is that okay?

**Comment by Palakkgoyal** [comment] 2023-06-26 06:41
Ok for me, What about you @VijayalakshmiGanesh?

**Comment by VijayalakshmiGanesh** [comment] 2023-06-26 07:20
> Ok for me, What about you @VijayalakshmiGanesh?

Works for me as well.

**Comment by Palakkgoyal** [comment] 2023-07-24 13:19
Can I work on this now?

**Comment by Palakkgoyal** [comment] 2023-07-25 05:56
Yes, sure. I think level2 is enough for it.

**Closed** 2023-07-29 11:35 UTC
Labels: level3, gssoc23
