### ISSUE TITLE
When too much scroll site crash.

### ISSUE THREAD

**Issue by furkangunduz** [narayan954/dummygram#73] opened 2022-10-06 07:42 UTC
### Description

When you scroll to reach end of the page it gives crash. 

### Steps to reproduce

Scroll to the end.

### Screenshots

![issue](https://user-images.githubusercontent.com/81353673/194247042-6aedf33e-c3af-42b0-adf0-3d03dc6881ac.PNG)

**Comment by narayan954** [comment] 2022-10-06 09:17
So, you really went to the bottom xD , Jokes apart, it could be due to some loophole in calculation of next posts to be displayed. 
Would you like to work on this? If so, feel free to!
Thank you!

**Comment by Furkangunduz** [comment] 2022-10-10 08:39
Unfortunately i couldnt work on this. if you want you can assign someone else who wants to solve this issue.

**Comment by narayan954** [comment] 2022-10-10 09:22
it's okay @Furkangunduz

**Comment by bhoopesh369** [comment] 2022-10-18 14:21
can i work on this
@narayan954

**Comment by narayan954** [comment] 2022-10-18 14:22
yes you can @bhoopesh369

**Comment by narayan954** [comment] 2022-12-03 18:40
open!

**Comment by AaryaaRam** [comment] 2022-12-05 17:06
Sir, I think this issue has already been fixed, cuz I am not getting it when I have scrolled to the bottom of the page.

**Comment by narayan954** [comment] 2022-12-06 05:25
yes, you seem right @AaryaaRam. I thought maybe due to some mistake while calculating the next posts to be loaded caused this issue, but this doesn't seem to happen anymore.
The issue can't be reproduced, so closing this

**Closed as not planned** 2022-12-06 05:25 UTC
Labels: intermediate, medium, bug
