### ISSUE TITLE
[FEATURE] Update edit form UI

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1099] opened 2023-08-02 16:57 UTC
### Description

The current UI of edit form is not so good looking. I want to update it.
I have the following design in mind.

### Screenshots

![images (2)](https://github.com/narayan954/dummygram/assets/116902573/62912fb7-6e6e-4702-9509-702c875355cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment] 2023-08-02 18:38
> ### Description
> The current UI of edit form is not so good looking. I want to update it. I have the following design in mind.
> 
> ### Screenshots
> ![images (2)](https://user-images.githubusercontent.com/116902573/257886284-62912fb7-6e6e-4702-9509-702c875355cf.jpeg)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

this loooks really good! but the issue is duplicate :/ #948 raises this issue. closing as duplicate

**Closed by narayan954** 2023-08-02 18:38 UTC
