### ISSUE TITLE
[FEATURE] UI(Thread): Improve Display for multi-images

### ISSUE THREAD

**Issue by mathiasayivor** [narayan954/dummygram#58] opened 2022-10-03 11:20 UTC
### Description

Currently, uploaded images are being displayed in grid form, but need some improvement (i.e too much gap for images with different heights)

We have a few options:

1. Use masonry style to display the upload's images on large devices but create a slider (aka carousel) on small devices
2. Carousel for both small and large devices

**Comment by Akshat2403** [comment] 2022-12-08 07:24
can you assign me this issue?

**Comment by narayan954** [comment] 2022-12-08 09:19
> can you assign me this issue?

Sure, go ahead and please confirm the program

**Comment by kshitij01042002** [comment] 2022-12-12 08:24
@narayan954 I can work on this..

**Comment by TheCharismaticEnigma** [comment] 2022-12-13 13:34
@narayan954 Hey! I'd like to work on this issue too . Even though I'm just a beginner, rolling and bouncing around like a turd in the wind trying to get used to the workflow, I'd love to add something of value and if you like my changes, you can merge them. I'd like to work on other issues too. Doesn't matter if you merge them or not. I'd just like to contribute to this project as much as possible.

**Comment by TheCharismaticEnigma** [comment] 2022-12-13 13:36
@narayan954 I know HTML AND CSS and I'm learning JS right now. So I'd take anything that you throw and I can handle.

**Comment by narayan954** [comment] 2022-12-13 13:42
> @narayan954 Hey! I'd like to work on this issue too . Even though I'm just a beginner, rolling and bouncing around like a turd in the wind trying to get used to the workflow, I'd love to add something of value and if you like my changes, you can merge them. I'd like to work on other issues too. Doesn't matter if you merge them or not. I'd just like to contribute to this project as much as possible.

Hi @TheCharismaticEnigma thanks a lot for showing such enthusiasm :) , I'd love to have you as a contributor ,but currently this issue is already assigned to @kshitij01042002 ,you may ask him or wait and see if the issue is unattended for 3 days ,you can claim it. Till then feel free to checkout other issues ,report some issue you find and help the open source grow. :)

Regards

**Comment by kshitij01042002** [comment] 2022-12-13 14:04
@TheCharismaticEnigma  I have already raised a PR for this one. 
You can run the project locally and find some bugs and raise a PR if you want

**Comment by narayan954** [comment] 2022-12-14 06:54
> @narayan954 I know HTML AND CSS and I'm learning JS right now. So I'll take anything that you throw and I'd be able to handle.

You can try improving UI components :)

**Comment by TheCharismaticEnigma** [comment] 2022-12-14 09:37
@kshitij01042002 @narayan954 
Hey man. I'm trying to run this on my local machine but I'm not able to break through. I tried to use git bash 
to open it but I'm not getting anything. I read the README file and followed the steps but got nowhere. I'd be glad if you could help me out

**Closed** 2022-12-14 22:49 UTC
Labels: ✨ goal: improvement, intermediate, Codepeak22
