### ISSUE TITLE
[FEATURE] Post image 

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#605] opened 2023-07-01 18:18 UTC
### Description

- When the user creats a post and uploads a picture, it doesn't get displayed in the post rather a default image is displayed in the background.
- I would like to display the uploaded image in the background of the post.

**Comment by narayan954** [comment] 2023-07-01 21:59
> ### I'm in GSSoC'23
> ### Description
> * When the user creats a post and uploads a picture, it doesn't get displayed in the post rather a default image is displayed in the background.
> * I would like to display the uploaded image in the background of the post.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_



> ### I'm in GSSoC'23
> ### Description
> * When the user creats a post and uploads a picture, it doesn't get displayed in the post rather a default image is displayed in the background.
> * I would like to display the uploaded image in the background of the post.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Hi @anamika7153 , I can't reproduce the error, can you recheck it?
![image](https://github.com/narayan954/dummygram/assets/77617189/90d9b47c-2279-4465-a9a1-61371db11acd)

**Comment by anamika7153** [comment] 2023-07-01 22:03
> > ### I'm in GSSoC'23
> > ### Description
> > 
> > * When the user creats a post and uploads a picture, it doesn't get displayed in the post rather a default image is displayed in the background.
> > * I would like to display the uploaded image in the background of the post.
> > 
> > ### Screenshots
> > _No response_
> > ### Additional information
> > _No response_
> 
> > ### I'm in GSSoC'23
> > ### Description
> > 
> > * When the user creats a post and uploads a picture, it doesn't get displayed in the post rather a default image is displayed in the background.
> > * I would like to display the uploaded image in the background of the post.
> > 
> > ### Screenshots
> > _No response_
> > ### Additional information
> > _No response_
> 
> Hi @anamika7153 , I can't reproduce the error, can you recheck it? ![image](https://user-images.githubusercontent.com/77617189/250310858-90d9b47c-2279-4465-a9a1-61371db11acd.png)

Yeah, it's fixed now.

**Comment by narayan954** [comment] 2023-07-01 22:06
> > > ### I'm in GSSoC'23
> > > ### Description
> > > 
> > > * When the user creats a post and uploads a picture, it doesn't get displayed in the post rather a default image is displayed in the background.
> > > * I would like to display the uploaded image in the background of the post.
> > > 
> > > ### Screenshots
> > > _No response_
> > > ### Additional information
> > > _No response_
> > 
> > 
> > > ### I'm in GSSoC'23
> > > ### Description
> > > 
> > > * When the user creats a post and uploads a picture, it doesn't get displayed in the post rather a default image is displayed in the background.
> > > * I would like to display the uploaded image in the background of the post.
> > > 
> > > ### Screenshots
> > > _No response_
> > > ### Additional information
> > > _No response_
> > 
> > 
> > Hi @anamika7153 , I can't reproduce the error, can you recheck it? ![image](https://user-images.githubusercontent.com/77617189/250310858-90d9b47c-2279-4465-a9a1-61371db11acd.png)
> 
> Yeah, it's fixed now.
that's good news, thanks :) Closing this issue

**Closed by narayan954** 2023-07-01 22:06 UTC
